version: 2
jobs:
  dev-build:
    docker: 
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Build Project
          command: npm run build
  
  dev-test:
    docker: 
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: npm install cypress
      - run:
          name: Run Cypress (In Headless)
          command: npx cypress run --headless

workflows:
  version: 2
  devstory-deployment:
    jobs:
      - dev-test
      - dev-build
