version: 2.1
jobs:
  build:
    docker:
      - image: vitiya99/react-base:1.0.0
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run: |
          npm install
          npm run build

  test:
    docker:
      - image: vitiya99/react-base:1.0.1
        auth:
          username: $DOCKER_USERNAME
          password: $DOCKER_PASSWORD
    steps:
      - checkout
      - run:
          name : Install Cypress
          command: npm install cypress
      - run:
          name : Install Cypress
          command: npx cypress run --headless
          

workflows:
  devstory-deployment:
    jobs:
      - build
      - test