jobs:
  build_deploy:
    machine: 
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: 
          name: Install AWS CLI
          command: |
            sudo apt-get update
            sudo apt install python3-pip
            sudo pip3 install awsebcli --upgrade
      - run:
          name: Install Packages
          command: npm install
      - run:
          name: Build Project
          command: npm run build
  
  ui_test:
    machine: 
      image: ubuntu-2004:202010-01

    steps:
      - checkout
      - run: 
          name: Install Cypress
          command: npm install cypress
      - run:
          name: Run Cypress (In Headless)
          command: npx cypress run --headless

workflows:
  version: 2
  execute_bulk:
    jobs:
      - ui_test
      - build_deploy
