version: 2.1
jobs:
  build:
    docker:
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run: |
          npm install
          npm run build
          npm install cypress
          npx cypress run --headless

  test:
    docker:
        - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run: |
          npm install
          npm run build
          npm install cypress
          npx cypress run --headless
          

workflows:
  devstory-deployment:
    jobs:
      - build
      - test