version: 2.1
orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@0.0.10
workflows:
  heroku_deploy:
    jobs:
      - build
      - ui-test
      - heroku/deploy-via-git:
          requires:
            - build
            - ui-test
          filters:
            branches:
              only: develop
jobs:
  build:
    docker:
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run:
          name: Install dependencies
          command: npm install
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
      - run:
          name: Run project
          command: npm run build
  ui-test:
    docker:
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run:
          name: Install Cypress
          command: npm install cypress
      - run:
          name: Run Cypress (In Headless)
          command: npx cypress run --headless
