version: 2.1
orbs:
  node: circleci/node@4.1.0
  heroku: circleci/heroku@0.0.10
workflows:
  devstory-deploy:
    jobs:
      - build
      - test
      - heroku/deploy-via-git:
          requires:
            - build
            - test
          filters:
            branches:
              only: develop
jobs:
  build:
    docker:
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - restore_cache:
          key: dependency-cache-{{ checksum "package.json" }}
      - run: |
          npm install
          npm run build
      - save_cache:
          key: dependency-cache-{{ checksum "package.json" }}
          paths:
            - ./node_modules
  test:
    docker:
      - image: vitiya99/react-base:1.0.1
    steps:
      - checkout
      - run: |
          npm cypress
          npx cypress run --headless
